view: v_llm_response {
  derived_table: {
    sql:
      SELECT
        timestamp,
        event_type,
        agent,
        session_id,
        invocation_id,
        user_id,
        trace_id,
        span_id,
        parent_span_id,
        status,
        error_message,
        is_truncated,
        JSON_QUERY(content, '$.response') AS response,
        COALESCE(CAST(JSON_VALUE(attributes, '$.usage_metadata.prompt_token_count') AS INT64), CAST(JSON_VALUE(content, '$.usage.prompt') AS INT64)) AS usage_prompt_tokens,
        COALESCE(CAST(JSON_VALUE(attributes, '$.usage_metadata.candidates_token_count') AS INT64), CAST(JSON_VALUE(content, '$.usage.completion') AS INT64)) AS usage_completion_tokens,
        COALESCE(CAST(JSON_VALUE(attributes, '$.usage_metadata.total_token_count') AS INT64), CAST(JSON_VALUE(content, '$.usage.total') AS INT64)) AS usage_total_tokens,
        CAST(JSON_VALUE(attributes, '$.usage_metadata.cached_content_token_count') AS INT64) AS usage_cached_tokens,
        SAFE_DIVIDE(CAST(JSON_VALUE(attributes, '$.usage_metadata.cached_content_token_count') AS INT64), COALESCE(CAST(JSON_VALUE(attributes, '$.usage_metadata.prompt_token_count') AS INT64), CAST(JSON_VALUE(content, '$.usage.prompt') AS INT64))) AS context_cache_hit_rate,
        CAST(JSON_VALUE(latency_ms, '$.total_ms') AS INT64) AS total_ms,
        CAST(JSON_VALUE(latency_ms, '$.time_to_first_token_ms') AS INT64) AS ttft_ms,
        JSON_VALUE(attributes, '$.model_version') AS model_version,
        JSON_QUERY(attributes, '$.usage_metadata') AS usage_metadata,
        JSON_QUERY(attributes, '$.cache_metadata') AS cache_metadata
      FROM `@{PROJECT_ID}.@{DATASET_NAME}.@{TABLE_NAME}`
      WHERE event_type = 'LLM_RESPONSE'
    ;;
  }

  dimension_group: timestamp {
    group_label: "IDs & Tracing"
    description: "The UTC timestamp when the event occurred."
    type: time
    sql: ${TABLE}.timestamp ;;
  }

  dimension: event_type {
    group_label: "Event Info"
    description: "The category of the event."
    type: string
    sql: ${TABLE}.event_type ;;
  }

  dimension: agent {
    group_label: "Event Info"
    description: "The name of the agent that generated this event."
    type: string
    sql: ${TABLE}.agent ;;
  }

  dimension: session_id {
    group_label: "IDs & Tracing"
    description: "A unique identifier for the entire conversation session."
    type: string
    sql: ${TABLE}.session_id ;;
  }

  dimension: invocation_id {
    group_label: "IDs & Tracing"
    description: "A unique identifier for a single turn or execution within a session."
    type: string
    hidden: yes
    sql: ${TABLE}.invocation_id ;;
  }

  dimension: user_id {
    group_label: "IDs & Tracing"
    description: "The identifier of the end-user participating in the session, if available."
    type: string
    sql: ${TABLE}.user_id ;;
  }

  dimension: trace_id {
    group_label: "IDs & Tracing"
    description: "OpenTelemetry trace ID for distributed tracing across services."
    type: string
    hidden: yes
    sql: ${TABLE}.trace_id ;;
  }

  dimension: span_id {
    group_label: "IDs & Tracing"
    description: "OpenTelemetry span ID for this specific operation."
    type: string
    hidden: yes
    sql: ${TABLE}.span_id ;;
  }

  dimension: parent_span_id {
    group_label: "IDs & Tracing"
    description: "OpenTelemetry parent span ID to reconstruct the operation hierarchy."
    type: string
    sql: ${TABLE}.parent_span_id ;;
  }

  dimension: status {
    group_label: "Event Info"
    description: "The outcome of the event, typically 'OK' or 'ERROR'."
    type: string
    sql: ${TABLE}.status ;;
  }

  dimension: error_message {
    group_label: "Event Info"
    description: "Detailed error message if the status is 'ERROR'."
    type: string
    sql: ${TABLE}.error_message ;;
  }

  dimension: is_truncated {
    group_label: "Event Info"
    description: "Boolean flag indicating if the content payload was truncated."
    type: yesno
    sql: ${TABLE}.is_truncated ;;
  }

  dimension: pk {
    primary_key: yes
    hidden: yes
    type: string
    sql: CONCAT(${trace_id}, '|', ${span_id}) ;;
    description: "Internal composite primary key for symmetric aggregates."
  }

  dimension: usage_total_tokens {
    group_label: "Token Usage"
    description: "The total number of tokens (prompt + completion) consumed by this specific LLM response."
    type: number
    sql: ${TABLE}.usage_total_tokens ;;
  }

  dimension: usage_prompt_tokens {
    group_label: "Token Usage"
    description: "The number of tokens consumed by the input prompt sent to the LLM."
    type: number
    sql: ${TABLE}.usage_prompt_tokens ;;
  }

  dimension: usage_completion_tokens {
    group_label: "Token Usage"
    description: "The number of tokens consumed by the output generated by the LLM."
    type: number
    sql: ${TABLE}.usage_completion_tokens ;;
  }

  dimension: usage_cached_tokens {
    group_label: "Token Usage"
    description: "The number of prompt tokens that were served from the context cache, reducing latency and cost."
    type: number
    sql: ${TABLE}.usage_cached_tokens ;;
  }

  dimension: context_cache_hit_rate {
    group_label: "Token Usage"
    description: "The percentage of the prompt that was served from the cache (cached tokens / total prompt tokens)."
    type: number
    sql: ${TABLE}.context_cache_hit_rate ;;
  }

  dimension: total_ms {
    group_label: "Latency"
    description: "The total wall-clock time in milliseconds the LLM took to process the request and generate the full response."
    type: number
    sql: ${TABLE}.total_ms ;;
  }

  dimension: ttft_ms {
    group_label: "Latency"
    description: "Time To First Token (TTFT). The latency in milliseconds before the LLM began streaming the first token of the response."
    type: number
    sql: ${TABLE}.ttft_ms ;;
  }

  dimension: model_version {
    group_label: "Event Info"
    description: "The specific version of the LLM model used for this request (e.g., 'gemini-2.5-flash')."
    type: string
    sql: ${TABLE}.model_version ;;
  }

  # --- BASE MEASURES ---

  measure: total_tokens_consumed {
    group_label: "Usage & Volume"
    type: sum
    sql: ${usage_total_tokens} ;;
    description: "Total tokens consumed across all LLM responses in the selected timeframe."
    drill_fields: [agent_events.timestamp_time, agent_events.agent, agent_events.user_id, agent_events.trace_id, model_version, total_ms]
    
    link: {
      label: "Show Tokens Over Time (Area Chart)"
      url: "@{VIZ_AREA_CHART}{{ link }}&fields=agent_events.timestamp_date,{{ _view._name }}.total_tokens_consumed&fill_fields=agent_events.timestamp_date&sorts=agent_events.timestamp_date+desc&limit=500&column_limit=50&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
    link: {
      label: "Top 5 Agents (for this selection)"
      url: "@{VIZ_BAR_CHART}{{ link }}&fields={{ _view._name }}.total_tokens_consumed,agent_events.agent&sorts={{ _view._name }}.total_tokens_consumed+desc&limit=5&column_limit=50&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
    link: {
      label: "Top 5 Users (for this selection)"
      url: "@{VIZ_BAR_CHART}{{ link }}&fields={{ _view._name }}.total_tokens_consumed,agent_events.user_id&sorts={{ _view._name }}.total_tokens_consumed+desc&limit=5&column_limit=50&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
  }

  measure: total_prompt_tokens {
    group_label: "Usage & Volume"
    type: sum
    sql: ${usage_prompt_tokens} ;;
    description: "Total prompt tokens consumed across all LLM responses."
    drill_fields: [agent_events.timestamp_time, agent_events.agent, agent_events.user_id, agent_events.trace_id, model_version, total_ms]
  }

  measure: total_completion_tokens {
    group_label: "Usage & Volume"
    type: sum
    sql: ${usage_completion_tokens} ;;
    description: "Total completion (candidate) tokens generated across all LLM responses."
    drill_fields: [agent_events.timestamp_time, agent_events.agent, agent_events.user_id, agent_events.trace_id, model_version, total_ms]
  }

  measure: total_llm_calls {
    group_label: "Usage & Volume"
    type: count_distinct
    sql: ${pk} ;;
    description: "Total number of successful LLM responses."
    drill_fields: [agent_events.timestamp_time, agent_events.agent, agent_events.user_id, agent_events.trace_id, model_version, total_ms]
    
    link: {
      label: "The Outlier Hunter (Scatter Plot)"
      url: "@{VIZ_SCATTER_CHART}{{ link }}&fields=agent_events.trace_id,{{ _view._name }}.total_llm_calls,{{ _view._name }}.total_tokens_consumed&sorts={{ _view._name }}.total_llm_calls+desc+0&limit=5000&column_limit=50&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
    link: {
      label: "Deep Log Inspector (Raw Table)"
      url: "@{VIZ_GRID_TABLE}{{ link }}&fields=agent_events.timestamp_time,agent_events.trace_id,agent_events.user_id,agent_events.agent,{{ _view._name }}.model_version,{{ _view._name }}.usage_total_tokens&sorts=agent_events.timestamp_time+desc&limit=500&column_limit=50&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
    link: {
      label: "User Footprint Over Time (Area Chart)"
      url: "@{VIZ_STACKED_AREA}{{ link }}&fields=agent_events.timestamp_date,agent_events.user_id,{{ _view._name }}.total_llm_calls&pivots=agent_events.user_id&sorts=agent_events.user_id,agent_events.timestamp_date+desc&limit=500&column_limit=10&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
  }

  measure: average_llm_latency {
    group_label: "Performance & Reliability"
    type: average
    sql: ${total_ms} ;;
    description: "Average latency for LLM responses in milliseconds."
    value_format_name: decimal_1
    drill_fields: []
    
    link: {
      label: "Latency vs Tokens (Scatter Plot)"
      url: "@{VIZ_SCATTER_CHART}{{ link }}&fields=agent_events.trace_id,{{ _view._name }}.total_ms,{{ _view._name }}.usage_total_tokens&sorts={{ _view._name }}.total_ms+desc&limit=1000&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
    link: {
      label: "Inspect Slowest Calls (Data Table)"
      url: "@{VIZ_GRID_TABLE}{{ link }}&fields=agent_events.timestamp_time,agent_events.trace_id,agent_events.agent,{{ _view._name }}.usage_total_tokens,{{ _view._name }}.total_ms&sorts={{ _view._name }}.total_ms+desc&limit=50&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
  }

  measure: p50_llm_latency {
    group_label: "Performance & Reliability"
    type: percentile
    percentile: 50
    sql: ${total_ms} ;;
    description: "Median (P50) latency for LLM responses in milliseconds."
    drill_fields: []
    
    link: {
      label: "Latency vs Tokens (Scatter Plot)"
      url: "@{VIZ_SCATTER_CHART}{{ link }}&fields=agent_events.trace_id,{{ _view._name }}.total_ms,{{ _view._name }}.usage_total_tokens&sorts={{ _view._name }}.total_ms+desc&limit=1000&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
    link: {
      label: "Inspect Slowest Calls (Data Table)"
      url: "@{VIZ_GRID_TABLE}{{ link }}&fields=agent_events.timestamp_time,agent_events.trace_id,agent_events.agent,{{ _view._name }}.usage_total_tokens,{{ _view._name }}.total_ms&sorts={{ _view._name }}.total_ms+desc&limit=50&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
  }

  measure: p75_llm_latency {
    group_label: "Performance & Reliability"
    type: percentile
    percentile: 75
    sql: ${total_ms} ;;
    description: "75th percentile latency for LLM responses in milliseconds."
    drill_fields: []
  }

  measure: p90_llm_latency {
    group_label: "Performance & Reliability"
    type: percentile
    percentile: 90
    sql: ${total_ms} ;;
    description: "90th percentile latency for LLM responses in milliseconds."
    drill_fields: []
    
    link: {
      label: "Latency vs Tokens (Scatter Plot)"
      url: "@{VIZ_SCATTER_CHART}{{ link }}&fields=agent_events.trace_id,{{ _view._name }}.total_ms,{{ _view._name }}.usage_total_tokens&sorts={{ _view._name }}.total_ms+desc&limit=1000&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
    link: {
      label: "Inspect Slowest Calls (Data Table)"
      url: "@{VIZ_GRID_TABLE}{{ link }}&fields=agent_events.timestamp_time,agent_events.trace_id,agent_events.agent,{{ _view._name }}.usage_total_tokens,{{ _view._name }}.total_ms&sorts={{ _view._name }}.total_ms+desc&limit=50&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
  }
  
  measure: p99_llm_latency {
    group_label: "Performance & Reliability"
    type: percentile
    percentile: 99
    sql: ${total_ms} ;;
    description: "99th percentile latency for LLM responses in milliseconds."
    drill_fields: []
    
    link: {
      label: "Latency vs Tokens (Scatter Plot)"
      url: "@{VIZ_SCATTER_CHART}{{ link }}&fields=agent_events.trace_id,{{ _view._name }}.total_ms,{{ _view._name }}.usage_total_tokens&sorts={{ _view._name }}.total_ms+desc&limit=1000&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
    link: {
      label: "Inspect Slowest Calls (Data Table)"
      url: "@{VIZ_GRID_TABLE}{{ link }}&fields=agent_events.timestamp_time,agent_events.trace_id,agent_events.agent,{{ _view._name }}.usage_total_tokens,{{ _view._name }}.total_ms&sorts={{ _view._name }}.total_ms+desc&limit=50&vis_config={{ vis_config | encode_uri }}&toggle=dat,pik,vis"
    }
  }

  # --- POP MEASURES: TOTAL TOKENS ---

  measure: pop_total_tokens_current {
    group_label: "PoP: Total Tokens Consumed"
    type: sum
    sql: ${usage_total_tokens} ;;
    filters: [agent_events.is_current_period: "yes"]
    description: "Total tokens consumed in the currently selected PoP date range."
  }

  measure: pop_total_tokens_previous {
    group_label: "PoP: Total Tokens Consumed"
    type: sum
    sql: ${usage_total_tokens} ;;
    filters: [agent_events.is_previous_period: "yes"]
    description: "Total tokens consumed in the previous period of the exact same length."
  }

  measure: pop_total_tokens_change {
    group_label: "PoP: Total Tokens Consumed"
    type: number
    value_format_name: percent_2
    sql: SAFE_DIVIDE(${pop_total_tokens_current} - ${pop_total_tokens_previous}, ${pop_total_tokens_previous}) ;;
    description: "The percentage change in total tokens between the current and previous period."
  }

  # --- POP MEASURES: PROMPT TOKENS ---

  measure: pop_prompt_tokens_current {
    group_label: "PoP: Prompt Tokens"
    type: sum
    sql: ${usage_prompt_tokens} ;;
    filters: [agent_events.is_current_period: "yes"]
    description: "Total prompt tokens consumed in the currently selected PoP date range."
  }

  measure: pop_prompt_tokens_previous {
    group_label: "PoP: Prompt Tokens"
    type: sum
    sql: ${usage_prompt_tokens} ;;
    filters: [agent_events.is_previous_period: "yes"]
    description: "Total prompt tokens consumed in the previous period."
  }

  measure: pop_prompt_tokens_change {
    group_label: "PoP: Prompt Tokens"
    type: number
    value_format_name: percent_2
    sql: SAFE_DIVIDE(${pop_prompt_tokens_current} - ${pop_prompt_tokens_previous}, ${pop_prompt_tokens_previous}) ;;
    description: "The percentage change in prompt tokens between the current and previous period."
  }

  # --- POP MEASURES: COMPLETION TOKENS ---

  measure: pop_completion_tokens_current {
    group_label: "PoP: Completion Tokens"
    type: sum
    sql: ${usage_completion_tokens} ;;
    filters: [agent_events.is_current_period: "yes"]
    description: "Total completion tokens generated in the currently selected PoP date range."
  }

  measure: pop_completion_tokens_previous {
    group_label: "PoP: Completion Tokens"
    type: sum
    sql: ${usage_completion_tokens} ;;
    filters: [agent_events.is_previous_period: "yes"]
    description: "Total completion tokens generated in the previous period."
  }

  measure: pop_completion_tokens_change {
    group_label: "PoP: Completion Tokens"
    type: number
    value_format_name: percent_2
    sql: SAFE_DIVIDE(${pop_completion_tokens_current} - ${pop_completion_tokens_previous}, ${pop_completion_tokens_previous}) ;;
    description: "The percentage change in completion tokens between the current and previous period."
  }

  # --- POP MEASURES: LLM CALLS ---

  measure: pop_llm_calls_current {
    group_label: "PoP: LLM Calls"
    type: count_distinct
    sql: ${pk} ;;
    filters: [agent_events.is_current_period: "yes"]
    description: "Total LLM calls in the currently selected PoP date range."
  }

  measure: pop_llm_calls_previous {
    group_label: "PoP: LLM Calls"
    type: count_distinct
    sql: ${pk} ;;
    filters: [agent_events.is_previous_period: "yes"]
    description: "Total LLM calls in the previous period."
  }

  measure: pop_llm_calls_change {
    group_label: "PoP: LLM Calls"
    type: number
    value_format_name: percent_2
    sql: SAFE_DIVIDE(${pop_llm_calls_current} - ${pop_llm_calls_previous}, ${pop_llm_calls_previous}) ;;
    description: "The percentage change in LLM calls between the current and previous period."
  }

  # --- EXECUTIVE FINOPS & DOLLAR SPEND MEASURES ---

  measure: total_spend_usd {
    group_label: "Executive FinOps Spend"
    description: "Total dollar spend USD calculated from input prompt tokens ($1.25/M) and output completion tokens ($5.00/M)."
    type: number
    value_format_name: usd
    sql: ROUND(SUM(${usage_prompt_tokens} * 0.00000125 + ${usage_completion_tokens} * 0.00000500), 4) ;;
  }

  measure: cost_per_session_usd {
    group_label: "Executive FinOps Spend"
    description: "Unit economics: average dollar cost per customer session."
    type: number
    value_format_name: usd
    sql: SAFE_DIVIDE(${total_spend_usd}, NULLIF(${agent_events.total_sessions}, 0)) ;;
  }

  measure: cache_hit_ratio_pct {
    group_label: "Executive FinOps Spend"
    description: "Percentage of prompt tokens served directly from Gemini Prompt Caching."
    type: number
    value_format_name: percent_2
    sql: SAFE_DIVIDE(SUM(${usage_cached_tokens}), NULLIF(SUM(${usage_prompt_tokens}), 0)) ;;
  }

  measure: cache_savings_usd {
    group_label: "Executive FinOps Spend"
    description: "Estimated dollar savings from Gemini prompt caching."
    type: number
    value_format_name: usd
    sql: ROUND(SUM(${usage_cached_tokens} * 0.00000094), 4) ;;
  }

}